### ISSUE TITLE
Odd height styling

### ISSUE THREAD

**Issue by stubbo** [HexaneNetworks/gamepanel-issues#7]
**Describe the bug**

**To Reproduce**
1. Go to a servers home page, should be most places from what i can tell

**Expected behavior**
Over sized webpage, like over complicating for something ;)

**Screenshots**
meh

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1809 build 17763.292
 - Browser Firefox nightly 67.0a1 (2019-01-29)(64bit)

**Additional context**
Some odd css... ```.Main {
    min-height: 1500px;```

**Comment by Hyrogenic** [comment]
Thank you for the report.

This issue is part of #4 and will be resolved shortly.
